branch-defaults:
  main:
    environment: Cas-api-alb-prod-env
    group_suffix: null
environment-defaults:
  Cas-api-alb-prod-env:
    branch: null
    repository: null
global:
  application_name: cas-api-alb-prod
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.13
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
  source_dir: .
