"""add new_table and new_column

Revision ID: 1d1c228560b6
Revises: f80c453d4c37
Create Date: 2025-03-25 08:42:36.837263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d1c228560b6'
down_revision: Union[str, None] = 'f80c453d4c37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cast_identity_verification', sa.Column('service_type', sa.Enum('A', 'B', 'AB'), nullable=False))
    op.add_column('cast_identity_verification', sa.Column('id_photo_media_id', sa.Integer(), nullable=True))
    op.add_column('cast_identity_verification', sa.Column('juminhyo_media_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cast_identity_verification', 'juminhyo_media_id')
    op.drop_column('cast_identity_verification', 'id_photo_media_id')
    op.drop_column('cast_identity_verification', 'service_type')
    # ### end Alembic commands ###
