"""add new_table and new_column

Revision ID: 281327a675a6
Revises: 736edf487ef7
Create Date: 2025-03-20 19:26:53.559331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '281327a675a6'
down_revision: Union[str, None] = '736edf487ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resv_reservation', sa.Column('reservation_note', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resv_reservation', 'reservation_note')
    # ### end Alembic commands ###
