"""add new_table and new_column

Revision ID: 3c258a3fc880
Revises: 5f7b16bd21dc
Create Date: 2025-03-10 18:14:31.503278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c258a3fc880'
down_revision: Union[str, None] = '5f7b16bd21dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resv_reservation_option', sa.Column('custom_name', sa.String(length=255), nullable=True))
    op.add_column('resv_reservation_option', sa.Column('status', sa.Enum('active', 'removed'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resv_reservation_option', 'status')
    op.drop_column('resv_reservation_option', 'custom_name')
    # ### end Alembic commands ###
