"""initial migration

Revision ID: 56dc63028856
Revises: 
Create Date: 2025-03-06 04:39:44.739631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '56dc63028856'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lines')
    op.drop_table('resv_chat')
    op.drop_index('email', table_name='users')
    op.drop_index('idx_invitation_id', table_name='users')
    op.drop_index('invitation_id', table_name='users')
    op.drop_index('line_id', table_name='users')
    op.drop_table('users')
    op.drop_table('resv_reservation')
    op.drop_table('pnt_details_course')
    op.drop_index('idx_cast_id', table_name='cast_traits')
    op.drop_index('unique_cast_trait', table_name='cast_traits')
    op.drop_table('cast_traits')
    op.drop_table('resv_reservation_option')
    op.drop_index('name', table_name='traits')
    op.drop_table('traits')
    op.drop_table('cast_common_prof')
    op.drop_table('pnt_details_rules')
    op.drop_table('pnt_user_point_balances')
    op.drop_index('name', table_name='cast_servicetype_list')
    op.drop_table('cast_servicetype_list')
    op.drop_index('rank_name', table_name='cast_rank')
    op.drop_table('cast_rank')
    op.drop_table('stations')
    op.drop_index('idx_cast_id', table_name='cast_servicetype')
    op.drop_table('cast_servicetype')
    op.drop_table('prefectures')
    op.drop_index('line_id', table_name='line_prefectures')
    op.drop_table('line_prefectures')
    op.drop_table('cast_prof_a')
    op.drop_index('idx_order_index', table_name='media_files')
    op.drop_index('idx_target_type_id', table_name='media_files')
    op.drop_table('media_files')
    op.drop_index('idx_cast_id', table_name='posts')
    op.drop_index('idx_created_at', table_name='posts')
    op.drop_table('posts')
    op.drop_table('popular_stations')
    op.drop_table('cast_prof_b')
    op.drop_index('cast_id', table_name='pnt_option_map')
    op.drop_index('id', table_name='pnt_option_map')
    op.drop_table('pnt_option_map')
    op.drop_index('id', table_name='pnt_details_option')
    op.drop_table('pnt_details_option')
    op.drop_table('bank')
    op.drop_index('name', table_name='cast_traits_list')
    op.drop_table('cast_traits_list')
    op.drop_table('pnt_point_transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pnt_point_transactions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('related_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('related_table', mysql.ENUM('reservation', 'event', 'coupon', 'purchase', 'manual'), nullable=True),
    sa.Column('transaction_type', mysql.ENUM('deposit', 'refund', 'release', 'event_bonus', 'manual_adjustment', 'purchase'), nullable=False),
    sa.Column('point_change', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('point_source', mysql.ENUM('regular', 'bonus'), server_default=sa.text("'regular'"), nullable=False),
    sa.Column('balance_after', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='pnt_point_transactions_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('cast_traits_list',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=50), server_default=sa.text("'その他'"), nullable=False),
    sa.Column('weight', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'cast_traits_list', ['name'], unique=True)
    op.create_table('bank',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invitation_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('bank_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('branch_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('account_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('account_number', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('account_holder', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('status', mysql.ENUM('ACTIVE', 'UNVERIFIED', 'INACTIVE', 'INVALID'), server_default=sa.text("'UNVERIFIED'"), nullable=True),
    sa.ForeignKeyConstraint(['invitation_id'], ['users.invitation_id'], name='bank_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('pnt_details_option',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('option_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('price', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('json_data', mysql.JSON(), nullable=True),
    sa.Column('sort_order', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'pnt_details_option', ['id'], unique=True)
    op.create_table('pnt_option_map',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('cast_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('option_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'pnt_option_map', ['id'], unique=True)
    op.create_index('cast_id', 'pnt_option_map', ['cast_id', 'option_id'], unique=True)
    op.create_table('cast_prof_b',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cast_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('free_area', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['cast_id'], ['cast_common_prof.cast_id'], name='fk_cast_b_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('popular_stations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('station_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rank', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name='popular_stations_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('posts',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('cast_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('photo_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('body', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('status', mysql.ENUM('public', 'private', 'draft'), server_default=sa.text("'public'"), nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('likes_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_created_at', 'posts', ['created_at'], unique=False)
    op.create_index('idx_cast_id', 'posts', ['cast_id'], unique=False)
    op.create_table('media_files',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_url', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('file_type', mysql.ENUM('image', 'video', 'document'), server_default=sa.text("'image'"), nullable=False),
    sa.Column('target_type', mysql.ENUM('profile_common', 'profile_a', 'profile_b', 'blog'), nullable=False),
    sa.Column('target_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_index', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_target_type_id', 'media_files', ['target_type', 'target_id'], unique=False)
    op.create_index('idx_order_index', 'media_files', ['target_id', 'order_index'], unique=False)
    op.create_table('cast_prof_a',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cast_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('free_area', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['cast_id'], ['cast_common_prof.cast_id'], name='fk_cast_a_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('line_prefectures',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('line_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prefecture_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], name='line_prefectures_ibfk_1'),
    sa.ForeignKeyConstraint(['prefecture_id'], ['prefectures.id'], name='line_prefectures_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('line_id', 'line_prefectures', ['line_id', 'prefecture_id'], unique=True)
    op.create_table('prefectures',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('cast_servicetype',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cast_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('servicetype_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['cast_id'], ['cast_common_prof.cast_id'], name='cast_servicetype_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servicetype_id'], ['cast_servicetype_list.id'], name='cast_servicetype_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_cast_id', 'cast_servicetype', ['cast_id'], unique=False)
    op.create_table('stations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('line_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pref_cd', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lon', mysql.FLOAT(), nullable=True),
    sa.Column('lat', mysql.FLOAT(), nullable=True),
    sa.Column('weight', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('e_sort', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], name='stations_ibfk_2'),
    sa.ForeignKeyConstraint(['pref_cd'], ['prefectures.id'], name='stations_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('cast_rank',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rank_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('base_fee', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('rank_name', 'cast_rank', ['rank_name'], unique=True)
    op.create_table('cast_servicetype_list',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=50), server_default=sa.text("'その他'"), nullable=False),
    sa.Column('weight', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'cast_servicetype_list', ['name'], unique=True)
    op.create_table('pnt_user_point_balances',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('regular_point_balance', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('bonus_point_balance', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('total_point_balance', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('last_updated', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='pnt_user_point_balances_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('pnt_details_rules',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rule_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('rule_description', mysql.TEXT(), nullable=True),
    sa.Column('transaction_type', mysql.ENUM('reservation_payment', 'reservation_reward', 'event_bonus', 'coupon_bonus'), nullable=False),
    sa.Column('point_type', mysql.ENUM('regular', 'bonus'), nullable=False),
    sa.Column('point_value', mysql.FLOAT(), nullable=False),
    sa.Column('is_addition', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('additional_data', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('cast_common_prof',
    sa.Column('cast_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cast_type', mysql.SET('A', 'B'), nullable=True),
    sa.Column('rank_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bust', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cup', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('waist', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hip', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('birthplace', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('blood_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('hobby', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('profile_image_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('reservation_fee', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('popularity', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('rating', mysql.FLOAT(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('self_introduction', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('job', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('dispatch_prefecture', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('support_area', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('available_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['cast_id'], ['users.id'], name='fk_cast_user', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rank_id'], ['cast_rank.id'], name='fk_cast_rank', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('cast_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('traits',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'traits', ['name'], unique=True)
    op.create_table('resv_reservation_option',
    sa.Column('reservation_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('option_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('option_price', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['pnt_details_option.id'], name='resv_reservation_option_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reservation_id', 'option_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('cast_traits',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cast_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trait_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['cast_id'], ['cast_common_prof.cast_id'], name='cast_traits_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trait_id'], ['cast_traits_list.id'], name='cast_traits_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('unique_cast_trait', 'cast_traits', ['cast_id', 'trait_id'], unique=True)
    op.create_index('idx_cast_id', 'cast_traits', ['cast_id'], unique=False)
    op.create_table('pnt_details_course',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_type', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('duration_minutes', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cost_points', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_fee_points', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cast_reward_points', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('additional_rules', mysql.JSON(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('resv_reservation',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cast_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_points', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('option_points', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('reservation_fee', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('total_points', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cast_reward_points', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('start_time', mysql.TIME(), nullable=False),
    sa.Column('end_time', mysql.TIME(), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('status', mysql.ENUM('requested', 'modified_by_cast', 'awaiting_user_confirmation', 'awaiting_deposit', 'confirmed', 'completed', 'canceled_user', 'canceled_cast'), server_default=sa.text("'requested'"), nullable=False),
    sa.Column('point_status', mysql.ENUM('pending', 'deposited', 'released', 'refunded'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['cast_id'], ['users.id'], name='resv_reservation_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['pnt_details_course.id'], name='resv_reservation_ibfk_3', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='resv_reservation_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nick_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('prefectures', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('line_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('invitation_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('tracking_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('phone_verified', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('phone_verification_code', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('mobile_phone', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('picture_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('sex', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('birth', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('affi_type', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_login', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('setup_status', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('line_id', 'users', ['line_id'], unique=True)
    op.create_index('invitation_id', 'users', ['invitation_id'], unique=True)
    op.create_index('idx_invitation_id', 'users', ['invitation_id'], unique=False)
    op.create_index('email', 'users', ['email'], unique=True)
    op.create_table('resv_chat',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reservation_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('sender_type', mysql.ENUM('user', 'cast'), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('lines',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('line_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('lon', mysql.FLOAT(), nullable=True),
    sa.Column('lat', mysql.FLOAT(), nullable=True),
    sa.Column('zoom', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('e_sort', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
