"""add new_table and new_column

Revision ID: 5f7b16bd21dc
Revises: f3bcd63a3f8a
Create Date: 2025-03-10 15:01:31.674008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f7b16bd21dc'
down_revision: Union[str, None] = 'f3bcd63a3f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'resv_reservation_option', 'resv_reservation', ['reservation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resv_reservation_option', type_='foreignkey')
    # ### end Alembic commands ###
