"""add new_table and new_column

Revision ID: 63633ef19cce
Revises: 3c258a3fc880
Create Date: 2025-03-10 20:28:31.725721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63633ef19cce'
down_revision: Union[str, None] = '3c258a3fc880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resv_status_detail', sa.Column('color_code', sa.String(length=7), nullable=True, comment='ステータスの表示カラー（例: #FF0000）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resv_status_detail', 'color_code')
    # ### end Alembic commands ###
