"""add new_table and new_column

Revision ID: 736edf487ef7
Revises: 63633ef19cce
Create Date: 2025-03-15 16:16:46.653720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '736edf487ef7'
down_revision: Union[str, None] = '63633ef19cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station_distances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_station_id', sa.Integer(), nullable=False),
    sa.Column('to_station_id', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['from_station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_station_id', 'to_station_id', name='from_to_idx')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('station_distances')
    # ### end Alembic commands ###
