"""add new_table and new_column

Revision ID: 7816ecfa008f
Revises: 281327a675a6
Create Date: 2025-03-22 21:37:30.934458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7816ecfa008f'
down_revision: Union[str, None] = '281327a675a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resv_reservation', sa.Column('station_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resv_reservation', 'stations', ['station_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resv_reservation', type_='foreignkey')
    op.drop_column('resv_reservation', 'station_id')
    # ### end Alembic commands ###
