"""add new_table and new_column

Revision ID: 97d9a40ce3c8
Revises: 7816ecfa008f
Create Date: 2025-03-23 22:13:01.578662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '97d9a40ce3c8'
down_revision: Union[str, None] = '7816ecfa008f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cast_favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cast_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cast_id'], ['cast_common_prof.cast_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'cast_id', name='unique_user_cast_favorite')
    )
    op.create_index(op.f('ix_cast_favorites_id'), 'cast_favorites', ['id'], unique=False)
    op.drop_constraint('resv_reservation_ibfk_4', 'resv_reservation', type_='foreignkey')
    op.drop_column('resv_reservation', 'station_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resv_reservation', sa.Column('station_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('resv_reservation_ibfk_4', 'resv_reservation', 'stations', ['station_id'], ['id'])
    op.drop_index(op.f('ix_cast_favorites_id'), table_name='cast_favorites')
    op.drop_table('cast_favorites')
    # ### end Alembic commands ###
