"""add new_table and new_column

Revision ID: a9ec65745ef2
Revises: c32d3b5a2e6b
Create Date: 2025-03-10 09:37:32.756270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9ec65745ef2'
down_revision: Union[str, None] = 'c32d3b5a2e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resv_status_detail',
    sa.Column('status_key', sa.String(length=50), nullable=False, comment='予約のステータスキー（例: requested, confirmed）'),
    sa.Column('user_label', sa.String(length=50), nullable=False, comment='ユーザー向け表示文言'),
    sa.Column('cast_label', sa.String(length=50), nullable=False, comment='キャスト向け表示文言'),
    sa.Column('description', sa.Text(), nullable=True, comment='ステータスの説明（例: ユーザーが予約をリクエストした状態）'),
    sa.Column('display_order', sa.Integer(), nullable=False, comment='表示順（例: 1=リクエスト中, 2=確定, 3=完了）'),
    sa.PrimaryKeyConstraint('status_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resv_status_detail')
    # ### end Alembic commands ###
