"""add new_table and new_column

Revision ID: db67f6801adc
Revises: 97d9a40ce3c8
Create Date: 2025-03-24 23:39:46.345426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db67f6801adc'
down_revision: Union[str, None] = '97d9a40ce3c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cast_identity_verification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cast_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('unsubmitted', 'pending', 'approved', 'rejected'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cast_id'], ['cast_common_prof.cast_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cast_id', 'cast_identity_verification', ['cast_id'], unique=False)
    op.create_index('idx_status', 'cast_identity_verification', ['status'], unique=False)
    op.create_index(op.f('ix_cast_identity_verification_id'), 'cast_identity_verification', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cast_identity_verification_id'), table_name='cast_identity_verification')
    op.drop_index('idx_status', table_name='cast_identity_verification')
    op.drop_index('idx_cast_id', table_name='cast_identity_verification')
    op.drop_table('cast_identity_verification')
    # ### end Alembic commands ###
