"""add new_table and new_column

Revision ID: f3bcd63a3f8a
Revises: a9ec65745ef2
Create Date: 2025-03-10 14:27:26.602873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3bcd63a3f8a'
down_revision: Union[str, None] = 'a9ec65745ef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resv_reservation', sa.Column('traffic_fee', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resv_reservation', 'traffic_fee')
    # ### end Alembic commands ###
