name: Deploy to AWS Lambda

on:
  push:
    branches:
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 800067001720.dkr.ecr.ap-northeast-1.amazonaws.com

    - name: Build and Push Docker image
      run: |
        docker build -t my-fastapi-app .
        docker tag my-fastapi-app:latest 800067001720.dkr.ecr.ap-northeast-1.amazonaws.com/my-fastapi-app:${{ github.ref_name }}
        docker push 800067001720.dkr.ecr.ap-northeast-1.amazonaws.com/my-fastapi-app:${{ github.ref_name }}

    - name: Update AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name Hello-${{ github.ref_name }} \
          --image-uri 800067001720.dkr.ecr.ap-northeast-1.amazonaws.com/my-fastapi-app:${{ github.ref_name }} \
          --region ap-northeast-1

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
