name: Deploy to AWS Fargate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # リポジトリのコードをチェックアウト
    - name: Checkout code
      uses: actions/checkout@v2

    # 環境変数の設定 (固定で fastapi-staging-service)
    - name: Set environment variables
      run: echo "SERVICE_NAME=fastapi-staging-service" >> $GITHUB_ENV

    # Amazon ECR ログイン
    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 800067001720.dkr.ecr.ap-northeast-1.amazonaws.com

    # Docker イメージをビルドしてプッシュ
    - name: Build and Push Docker image
      run: |
        IMAGE_TAG=800067001720.dkr.ecr.ap-northeast-1.amazonaws.com/my-fastapi-app:${{ github.sha }}
        docker buildx build --platform linux/amd64 -t $IMAGE_TAG .
        docker push $IMAGE_TAG

    # ECS タスク定義を新規リビジョンとして登録
    - name: Register ECS Task Definition
      run: |
        aws ecs register-task-definition \
          --family Fargate \
          --container-definitions "[
            {
              \"name\": \"fastapi-container\",
              \"image\": \"800067001720.dkr.ecr.ap-northeast-1.amazonaws.com/my-fastapi-app:${{ github.sha }}\",
              \"essential\": true,
              \"portMappings\": [
                {
                  \"containerPort\": 8000,
                  \"hostPort\": 8000
                }
              ],
              \"environment\": [
                {
                  \"name\": \"MESSAGE\",
                  \"value\": \"こんちわ、これは環境変数\"
                }
              ],
              \"logConfiguration\": {
                \"logDriver\": \"awslogs\",
                \"options\": {
                  \"awslogs-group\": \"/ecs/fastapi-container\",
                  \"awslogs-region\": \"ap-northeast-1\",
                  \"awslogs-stream-prefix\": \"ecs\"
                }
              }
            }
          ]" \
          --region ap-northeast-1

    # ECS サービスを更新
    - name: Update ECS Service
      run: |
        echo "Deploying to service: $SERVICE_NAME"
        aws ecs update-service \
          --cluster my-fargate-cluster \
          --service $SERVICE_NAME \
          --force-new-deployment \
          --region ap-northeast-1

    # ECS タスクの状態を確認
    - name: Check ECS Task Status
      run: |
        TASK_ARN=$(aws ecs list-tasks --cluster my-fargate-cluster --service-name $SERVICE_NAME --desired-status RUNNING --region ap-northeast-1 --query 'taskArns[0]' --output text)
        if [ "$TASK_ARN" == "None" ]; then
          echo "No running tasks found for service: $SERVICE_NAME"
          exit 1
        fi
        aws ecs describe-tasks \
          --cluster my-fargate-cluster \
          --tasks $TASK_ARN \
          --region ap-northeast-1

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
