name: Deploy to AWS Fargate

on:
  push:
    branches:
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # 環境変数の設定 (ブランチに基づく)
    - name: Set environment variables
      run: echo "ENVIRONMENT=${{ github.ref_name }}" >> $GITHUB_ENV

    # デバッグ: 環境変数の確認
    - name: Debug ENVIRONMENT
      run: echo "Branch: $ENVIRONMENT"

    # Amazon ECR ログイン
    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 800067001720.dkr.ecr.ap-northeast-1.amazonaws.com

    # Docker イメージのビルドとプッシュ
    - name: Build and Push Docker image
      run: |
        IMAGE_TAG=800067001720.dkr.ecr.ap-northeast-1.amazonaws.com/my-fastapi-app:${{ github.sha }}
        docker build -t $IMAGE_TAG .
        docker push $IMAGE_TAG

    # ECS サービスの更新 (固定で fastapi-staging-service を使用)
    - name: Update ECS Service
      run: |
        aws ecs update-service \
          --cluster my-fargate-cluster \
          --service fastapi-staging-service \
          --force-new-deployment \
          --region ap-northeast-1

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
